config/routes.rb
Rails.application.routes.draw do

  #Defino la ruta principal de la página
  root 'home#index'

  devise_for :administrators
  resources :administrators, except: :create
  resources :administrators, controllers: { registrations: 'registrations' }
  resources :books 
  resources :genres
  resources :tags
  resources :parts
  resources :trailers
  devise_for :subscribers
  resources :editorials
  resources :authors
  resources :profiles
  resources :news
  resources :reviews

  get '/admin_panel', to: 'adminpanel#admin_panel'
  get "/admin_panel/create_admin" => "adminpanel#new_admin"
  post "/admin_panel/create_admin" => "adminpanel#create_admin"
  get "/admin_panel/show_admin" => "adminpanel#show_admin"  
  get "/admin_panel/index_admin" => "adminpanel#index_admin" 
  delete "/admin_panel/index_admin" => "adminpanel#destroy"  
  get '/admin_panel/edit_pass' => 'adminpanel#edit_pass'
  patch '/admin_panel/edit_pass' => 'adminpanel#update_pass'

  get '/preguntas_frecuentes', to: 'informations#pregunta'
  get '/contacto', to: 'informations#contacto'
  get '/condicion', to: 'informations#condicion'
  get 'news/news_home' => 'news#news_home'
  
  get '/subscribers/edit_pass' => 'subscribers#edit_pass'
  patch '/subscribers/edit_pass' => 'subscribers#update_pass'
  
  post "/parts/:id/reading_part" => "parts#reading_part"
  delete "/parts/:id/unreading_part" => "parts#unreading_part"

  post "/books/:id/favorite_book" => "books#favorite_book"
  delete "/books/:id/unfavorite_book" => "books#unfavorite_book"
  
end

app/models/part.rb
class Part < ApplicationRecord
    #Atributos: url_document, position, normal_release_date, premium_release_date
    #Relaciones: book

    belongs_to :book
    
    validates :url_document, length: { minimum: 5 }
    validate :pdf_validation
    
    validates :position, presence: true, length:{ minimum:0 }
    validates :position, uniqueness: { scope: :book }

    validates :normal_release_date, presence: true
    validates :premium_release_date, presence: true
    validate :date_validation

    default_scope->{order("position")}
    private 
    def pdf_validation
        if (url_document.last(4)!='.pdf')
          self.errors[:base] << "No se coloco un enlace a un archivo pdf"
        end
    end
    def date_validation
      self.errors.add(:normal_release_date, "no esta en rango.") unless ((Date.today)..(3.years.from_now)).include?(self.normal_release_date)
      self.errors.add(:premium_release_date, "no esta en rango.") unless ((Date.today)..(3.years.from_now)).include?(self.premium_release_date)
    end
    def part_validation
      if (url_document.last(4)!='.pdf')
        self.errors[:base] << "No se coloco un enlace a un archivo pdf"
      end
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController

    before_action :authenticate_administrator!, except: [:show, :reading_part,:unreading_part], if: :subscriber_signed_in?
    before_action :authenticate_scope!

    def new
        #render plain: params[:part].inspect 
        @part = Part.new
        @books = Book.all
        
    end

    def create
        #render plain: params[:part].inspect        
        @books = Book.all
        @part = Part.new(part_params)
        if @part.save
            redirect_to @part
        else
                render 'new'
        end
    end

    def show
        @part = Part.find(params[:id])
        if cookies[:current_profile_id] != nil
            @reading = Reading.find_by(part_id: params[:id],profile_id:cookies[:current_profile_id])
        end
    end

    def index
        @parts = Part.all
    end

    def edit
        @books = Book.all
        @part = Part.find(params[:id])
    end

    def update
        @books = Book.all
        @part = Part.find(params[:id])
        if @part.update(part_params)
        redirect_to @part
        else
        render 'edit'
        end
    end

    def destroy
        @part = Part.find(params[:id])
        id_book = @part.book.id 
        @part.destroy
        #redirect_to parts_path
        redirect_to :controller => 'books', :action => 'show', :id => params[:book_id], :removed_part => @part.position
    end

    def reading_part
        if cookies[:current_profile_id] != nil
            reading = Reading.new(state:'READ',part_id:params[:id].to_i,profile_id:cookies[:current_profile_id].to_i)
            if reading.save
                part = reading.part
                redirect_to :controller => 'parts', :action => 'show', :id => params[:id]
            else
                redirect_to root_path
            end
        end
    end

    def unreading_part
        if cookies[:current_profile_id] != nil
            reading = Reading.find_by(part_id:params[:id]) 
            reading.destroy
            redirect_to :controller => 'parts', :action => 'show', :id => params[:id]
        end
    end

    private
    def part_params
        params.require(:part).permit(:document, :position, :normal_release_date, :premium_release_date, :book_id, :url_document,:id)
    end
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/parts/_form.html.erb
<%=form_for @part do |f| %>
  <% if @part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@part.errors.count, "error") %></h2>
      No se pudo guardar la parte por:
      <ul>
        <% @part.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label(:book_id,"Libro") %><br />
    <% if params['book_id']!=nil %>
      <%= f.label(:book_id,@books.find(params['book_id']).title) %>
      <%= f.hidden_field(:book_id, :value => params['book_id'] ) %>
    <%else%>
      <%= f.select(:book_id, options_for_select(@books.map{ |book| [book.title,book.id] }), {:class => 'custom-select'}) %>
    <%end%>
  </p>
  <p>
    <%= f.label(:pdf,"Url del documento") %><br />
    <%= f.text_field(:url_document, {:class => 'form-control', :required => true})%>
  </p>
  <p>
    <%= f.label(:position,"Posición") %><br />
    <%= f.number_field(:position, {:class => 'form-control', :required => true})%>
  </p>
  <p>
    <%= f.label(:normal_release_date,"Fecha de lanzamiento suscriptor normal") %><br />
    <%= f.date_field(:normal_release_date, {:class => 'form-control', :required => true}) %>
  </p>
  <p>
    <%= f.label(:premium_release_date,"Fecha de lanzamiento suscriptor premium") %><br />
    <%= f.date_field(:premium_release_date, {:class => 'form-control', :required => true}) %>
  </p>
  <%= f.submit('Cargar parte',{:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/parts/edit.html.erb
<h1>Editar Parte</h1>
<%= render 'form' %>
<%= link_to 'Regresar', url_for(:back) %>

app/views/parts/index.html.erb
<h1>Listado de Partes</h1>
<%= link_to 'Agregar parte', new_part_path %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Libro</th>
      <th scope="col">Parte del libro</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.book.title %></td>
        <td><%= part.position %></td>
        <td>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Ver', part_path(part), {:style=>'color: inherit;'}%>
          </button>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Editar', edit_part_path(part), {:style=>'color: inherit;'} %>
          </button>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Borrar', part_path(part), method: :delete, data: {confirm: 'Seguro que quieres eliminarlo?'},:style=>'color: inherit;'%>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parts/new.html.erb
<h1>Nueva Parte</h1>
<%= render 'form' %>
<%= link_to 'Regresar', url_for(:back) %>

app/views/parts/show.html.erb
<% if administrator_signed_in? %>
  <h1>Detalle de la parte</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Libro: </th>
        <td><%= @part.book.title %></td>
      </tr>
      <tr>
        <th scope="row">Url Documento: </th>
        <td><%= @part.url_document %></td>
      </tr>
      <tr>
        <th scope="row">Posición: </th>
        <td><%= @part.position %></td>
      </tr>
      <tr>
        <th scope="row">Fecha de lanzamiento suscriptor normal: </th>
        <td><%= @part.normal_release_date %></td>
      </tr>
      <tr>
        <th scope="row">Fecha de lanzamiento suscriptor premium: </th>
        <td><%= @part.premium_release_date %></td>
      </tr>
    </tbody>
  </table>
<% end %>
<embed src=<%=  @part.url_document+'#toolbar=0' %> type="application/pdf" width="100%" height="1000" style="margin:10px;">
<% if !administrator_signed_in?%>
  <div class="d-flex justify-content-center align-items-center">
    <% if @reading == nil %>
      <%= form_for Reading.new, url: '/parts/'+@part.id.to_s+'/reading_part' do |f|%>
        <%= f.hidden_field(:id, :value => @part.id ) %>
        <%= f.submit('Parte Leida',{:class => 'btn btn-danger'}) %>
      <%end%>
    <%else%>
      <h4 style="margin:10px">Parte Leida</h4>
      <%= link_to 'x', '/parts/'+@part.id.to_s+'/unreading_part', :id => @part.id.to_s, method: :delete, data: {confirm: 'Seguro que quieres eliminarlo?'},:class => 'btn btn-danger'%>
    <% end %>
  </div>
<%end%>
<%= link_to 'Regresar', url_for(:back) %>