config/routes.rb
Rails.application.routes.draw do

  #Defino la ruta principal de la página
  root 'home#index'

  devise_for :administrators
  resources :administrators, except: :create
  resources :administrators, controllers: { registrations: 'registrations' }
  resources :books 
  resources :genres
  resources :tags
  resources :parts
  resources :trailers
  devise_for :subscribers
  resources :editorials
  resources :authors
  resources :profiles
  resources :news
  resources :reviews

  get '/admin_panel', to: 'adminpanel#admin_panel'
  get "/admin_panel/create_admin" => "adminpanel#new_admin"
  post "/admin_panel/create_admin" => "adminpanel#create_admin"
  get "/admin_panel/show_admin" => "adminpanel#show_admin"  
  get "/admin_panel/index_admin" => "adminpanel#index_admin" 
  delete "/admin_panel/index_admin" => "adminpanel#destroy"  
  get '/admin_panel/edit_pass' => 'adminpanel#edit_pass'
  patch '/admin_panel/edit_pass' => 'adminpanel#update_pass'

  get '/preguntas_frecuentes', to: 'informations#pregunta'
  get '/contacto', to: 'informations#contacto'
  get '/condicion', to: 'informations#condicion'
  get 'news/news_home' => 'news#news_home'
  
  get '/subscribers/edit_pass' => 'subscribers#edit_pass'
  patch '/subscribers/edit_pass' => 'subscribers#update_pass'
  
  post "/parts/:id/reading_part" => "parts#reading_part"
  delete "/parts/:id/unreading_part" => "parts#unreading_part"

  post "/books/:id/favorite_book" => "books#favorite_book"
  delete "/books/:id/unfavorite_book" => "books#unfavorite_book"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @books = Book.all
    @noticias = News.limit(3)
    @profiles = Profile.all
    @books_suggested = books_suggested()
  end

  private

  def books_suggested
    books = Book.all
    readings = Reading.all.select { |element| element.profile_id == cookies[:current_profile_id].to_i }
    actual_books = books.select { |book| book.parts.any? { |part| readings.any?{ |reading| reading.part_id == part.id} }}
    genres_id = actual_books.collect{|book| book.genre_id}
    suggested = books.select { |book| genres_id.any? { |genre_id| genre_id==book.genre_id } && !actual_books.any?{ |actual| actual.id == book.id} }
    return suggested
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if subscriber_signed_in? || administrator_signed_in? %>
  <div style="margin:20px">
    <%= render :template => 'news/news_home', :collection => @noticias%>
  </div>
  <% if @books_suggested.size != 0%>
    <p>
      <h4>Libros recomendados</h4>
      <div class="card-columns" style="margin-top:10px">
        <% @books_suggested.each do |book| %>
          <% if book.visibility %>
            <div class="card align-items-center text-center" style="border: none;" >
              <img src=<%=book.url_cover%> class="card-img-top" alt=<%=book.title%> style="width:200px; height:300;overflow: hidden;">
              <div class="card-body">
                <h5 class="card-title">
                  <%= link_to book.title, book_path(book), {:style=>'color: inherit;'}%>
                </h5>
                <p class="card-text"><%= book.autor %></p>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <% if administrator_signed_in? %>
                    <button type="button" class="btn btn-dark">
                      <%= link_to 'Ver', book_path(book), {:style=>'color: inherit;'}%>
                    </button>
                    <button type="button" class="btn btn-dark">
                      <%= link_to 'Editar', edit_book_path(book), {:style=>'color: inherit;'} %>
                    </button>
                    <button type="button" class="btn btn-dark">
                      <%= link_to 'Borrar', book_path(book), method: :delete, data: {confirm: 'Seguro que quieres eliminarlo?'},:style=>'color: inherit;'%>
                    </button>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </p>
  <%end%>
  <p>
    <h4>Todos los libros</h4>
    <%= render :template => 'books/index', :collection => @books%>
  </p>
<% else %>
  <div class="text-center">
    <h3>Bienvenido a Bookflix!</h3>
  </div>
<% end%>