config/routes.rb
Rails.application.routes.draw do

  #Defino la ruta principal de la página
  root 'home#index'

  devise_for :administrators
  resources :administrators, except: :create
  resources :administrators, controllers: { registrations: 'registrations' }
  resources :books 
  resources :genres
  resources :tags
  resources :parts
  resources :trailers
  devise_for :subscribers
  resources :editorials
  resources :authors
  resources :profiles
  resources :news
  resources :reviews

  get '/admin_panel', to: 'adminpanel#admin_panel'
  get "/admin_panel/create_admin" => "adminpanel#new_admin"
  post "/admin_panel/create_admin" => "adminpanel#create_admin"
  get "/admin_panel/show_admin" => "adminpanel#show_admin"  
  get "/admin_panel/index_admin" => "adminpanel#index_admin" 
  delete "/admin_panel/index_admin" => "adminpanel#destroy"  
  get '/admin_panel/edit_pass' => 'adminpanel#edit_pass'
  patch '/admin_panel/edit_pass' => 'adminpanel#update_pass'

  get '/preguntas_frecuentes', to: 'informations#pregunta'
  get '/contacto', to: 'informations#contacto'
  get '/condicion', to: 'informations#condicion'
  get 'news/news_home' => 'news#news_home'
  
  get '/subscribers/edit_pass' => 'subscribers#edit_pass'
  patch '/subscribers/edit_pass' => 'subscribers#update_pass'
  
  post "/parts/:id/reading_part" => "parts#reading_part"
  delete "/parts/:id/unreading_part" => "parts#unreading_part"

  post "/books/:id/favorite_book" => "books#favorite_book"
  delete "/books/:id/unfavorite_book" => "books#unfavorite_book"
  
end

app/models/news.rb
class News < ApplicationRecord

    #Define un orden por default para listarlos
    default_scope->{order("created_at desc")}

    validates :title, length: { minimum: 5 }
    validates :title, :uniqueness => {:case_sensitive => false}
    validates :title, presence: true, allow_blank: false
    
    validates :content , length: { minimum: 15 }
    validates :content, presence: true, allow_blank: false

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    
    before_action :authenticate_administrator!, except: [:index], if: :subscriber_signed_in?
    before_action :authenticate_scope!
    
    def new
        @news = News.new
    end

    def create
        @news = News.new(news_params)
        if @news.save
            redirect_to :controller => 'news', :action => 'index', :add_success => @news.title
        else
            render 'new'
        end
    end

    def show
        @news = News.find(params[:id])
    end

    def index
        @news_index = News.all
    end





    def news_home
        @noticias = News.limit(3)  
    end
    




    
    def edit
        @news = News.find(params[:id])
    end

    def update
        @news = News.find(params[:id])
        if @news.update(news_params)
        redirect_to news_index_path
        else
            render 'edit'
        end
    end

    def destroy
        @news = News.find(params[:id])
        @news.destroy
        redirect_to news_index_path, :notice => "La noticia se elimino con exito."
    end

    private
    def news_params
        params.require(:news).permit( :title, :content, :publication_date)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%=form_for @news do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %></h2>
      No se pudo guardar la noticia por:
      <ul>
        <% @news.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Título %><br />
    <%= f.text_field(:title, {:class => 'form-control', :required => true}) %>
  </p>

  <p>
    <%= f.label :Contenido %><br />
    <%= f.text_field(:content, {:class => 'form-control', :required => true}) %>
  </p>

  <%= f.submit('Aceptar',{:class => 'btn btn-dark'}) %>
  
</p>
<% end %>

app/views/news/edit.html.erb
<h1>Editar Noticia</h1>
<%= render 'form' %>

<%= link_to 'Regresar', url_for(:back) %>

app/views/news/index.html.erb
<% if params['add_success']!=nil && current_subscriber==nil %>
  <div class="alert alert-success" role="alert" style="margin-top:20px;">
    Se ha agregado exitósamente la noticia: <%=params['add_success']%>
  </div>
<%end%>
<h1>Noticias</h1>
<% if administrator_signed_in? %>
  <%= link_to 'Agregar noticia', new_news_path %>
<% end %>
<div class="card-columns" style="margin-top:20px">
  <% @news_index.each do |noticia| %>
    <div class="card border-dark mb-3" style="width: 20rem;">
      <div class="card-body">
        <h5 class="card-title"><%=noticia.title%></h5>
        <p class= "card-text"><%=noticia.content%></p>
        <p class="card-text"><small class="text-muted"><%=noticia.created_at.to_s(:custom_datetime)%></small></p>
        <% if administrator_signed_in? %>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Editar', edit_news_path(noticia), {:style=>'color: inherit;'} %>
          </button>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Eliminar', news_path(noticia), method: :delete, data: {confirm: 'Seguro que quieres eliminar la noticia?'},:style=>'color: inherit;'%>
          </button>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/news/new.html.erb
<h1>Nueva Noticia</h1>
<%= render 'form' %>

<%= link_to 'Regresar', url_for(:back) %>

app/views/news/news_home.html.erb
<div class="container" style="background:#85929E; border-radius:30px;padding:10px">
  <h2 class="display-5">Noticias</h2>
  <p class="lead">
    <div class="card-columns">
      <% @noticias.each do |noticia| %>
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%=noticia.title.truncate_words(10)%></h5>
            <p class="card-text"><%=noticia.content.truncate_words(15)%></p>
            <p class="card-text"><small class="text-muted"><%=noticia.created_at.to_s(:custom_datetime)%></small></p>
            <a href="/news" class="btn btn-dark">Leer Más..</a>
          </div>
        </div>
      <% end %>
    </div>
  </p>
</div>

app/views/news/show.html.erb
<h2>hola
</h2>