config/routes.rb
Rails.application.routes.draw do

  #Defino la ruta principal de la página
  root 'home#index'

  devise_for :administrators
  resources :administrators, except: :create
  resources :administrators, controllers: { registrations: 'registrations' }
  resources :books 
  resources :genres
  resources :tags
  resources :parts
  resources :trailers
  devise_for :subscribers
  resources :editorials
  resources :authors
  resources :profiles
  resources :news
  resources :reviews

  get '/admin_panel', to: 'adminpanel#admin_panel'
  get "/admin_panel/create_admin" => "adminpanel#new_admin"
  post "/admin_panel/create_admin" => "adminpanel#create_admin"
  get "/admin_panel/show_admin" => "adminpanel#show_admin"  
  get "/admin_panel/index_admin" => "adminpanel#index_admin" 
  delete "/admin_panel/index_admin" => "adminpanel#destroy"  
  get '/admin_panel/edit_pass' => 'adminpanel#edit_pass'
  patch '/admin_panel/edit_pass' => 'adminpanel#update_pass'

  get '/preguntas_frecuentes', to: 'informations#pregunta'
  get '/contacto', to: 'informations#contacto'
  get '/condicion', to: 'informations#condicion'
  get 'news/news_home' => 'news#news_home'
  
  get '/subscribers/edit_pass' => 'subscribers#edit_pass'
  patch '/subscribers/edit_pass' => 'subscribers#update_pass'
  
  post "/parts/:id/reading_part" => "parts#reading_part"
  delete "/parts/:id/unreading_part" => "parts#unreading_part"

  post "/books/:id/favorite_book" => "books#favorite_book"
  delete "/books/:id/unfavorite_book" => "books#unfavorite_book"
  
end

app/models/trailer.rb
class Trailer < ApplicationRecord
    #Atributos: url_document, normal_release_date, premium_release_date
    #Relaciones: book

    belongs_to :book
    
    validates :book_id, uniqueness: true

    validate :pdf_validation

    validates :normal_release_date, presence: true
    validates :premium_release_date, presence: true
    validate :date_validation
    
    private 
    def pdf_validation
        if (url_document.last(4)!='.pdf')
          self.errors[:base] << "No se coloco un enlace a un archivo pdf"
        end
    end
    def date_validation
      self.errors.add(:normal_release_date, "no esta en rango.") unless ((Date.today)..(3.years.from_now)).include?(self.normal_release_date)
      self.errors.add(:premium_release_date, "no esta en rango.") unless ((Date.today)..(3.years.from_now)).include?(self.premium_release_date)
    end
end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
    
    before_action :authenticate_administrator!, except: [:show], if: :subscriber_signed_in?
    before_action :authenticate_scope!
    
    
    def new
        @trailer = Trailer.new
        @books = Book.all
    end

    def create
        #render plain: params[:trailer].inspect
        @books = Book.all
        @trailer = Trailer.new(trailer_params)
        if @trailer.save
            redirect_to @trailer
        else
                render 'new'
        end
    end

    def show
        @trailer = Trailer.find(params[:id])
    end

    def index
        @trailers = Trailer.all
    end

    def edit
        @books = Book.all
        @trailer = Trailer.find(params[:id])
    end

    def update
        @books = Book.all
        @trailer = Trailer.find(params[:id])
        if @trailer.update(trailer_params)
        redirect_to @trailer
        else
        render 'edit'
        end
    end

    def destroy
        @trailer = Trailer.find(params[:id])
        @trailer.destroy
        redirect_to :controller => 'books', :action => 'show', :id => @trailer.book.id, :removed_trailer => 'true'
        #redirect_to trailers_path
    end

    private
    def trailer_params
        params.require(:trailer).permit(:url_document, :normal_release_date, :premium_release_date, :book_id)
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%=form_for @trailer do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %></h2>
      No se pudo guardar el trailer por:
      <ul>
        <% @trailer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label(:book_id,"Libro") %><br />
    <% if @trailer.book!=nil %>
      <%= f.label(:book_id,@trailer.book.title) %>
      <%= f.hidden_field(:book_id, :value => @trailer.book.id ) %>
    <%elsif params['book_id']!=nil %>
      <%= f.label(:book_id,@books.find(params['book_id']).title) %>
      <%= f.hidden_field(:book_id, :value => params['book_id'] ) %>
    <%else%>
      <%= f.select(:book_id, options_for_select(@books.map{ |book| [book.title,book.id] }), {:class => 'custom-select'}) %>
    <%end%>
  </p>
  <p>
    <%= f.label(:url_document,"Url del documento") %><br />
    <%= f.text_field(:url_document, {:class => 'form-control', :required => true})%>
  </p>
  <%= f.label(:normal_release_date,"Fecha de lanzamiento suscriptor normal") %><br />
  <%= f.date_field(:normal_release_date, {:class => 'form-control', :required => true}) %>
</p>
<p>
  <%= f.label(:premium_release_date,"Fecha de lanzamiento suscriptor premium") %><br />
  <%= f.date_field(:premium_release_date, {:class => 'form-control', :required => true}) %>
</p>
<%= f.submit('Cargar trailer',{:class => 'btn btn-primary'}) %>
</p>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editar Trailer</h1>
<%= render 'form' %>
<%= link_to 'Regresar', url_for(:back) %>

app/views/trailers/index.html.erb
<h1>Listado de Trailers</h1>
<%= link_to 'Agregar trailer', new_trailer_path %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Trailer</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.book.title %></td>
        <td>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Ver', trailer_path(trailer), {:style=>'color: inherit;'}%>
          </button>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Editar', edit_trailer_path(trailer), {:style=>'color: inherit;'} %>
          </button>
          <button type="button" class="btn btn-dark">
            <%= link_to 'Borrar', trailer_path(trailer), method: :delete, data: {confirm: 'Seguro que quieres eliminarlo?'},:style=>'color: inherit;'%>
          </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trailers/new.html.erb
<h1>Nuevo Trailer</h1>
<%= render 'form' %>
<%= link_to 'Regresar', url_for(:back) %>

app/views/trailers/show.html.erb
<% if administrator_signed_in? %>
  <h1>Detalle del Trailer</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Libro: </th>
        <td><%= @trailer.book.title %></td>
      </tr>
      <tr>
        <th scope="row">Url Documento: </th>
        <td><%= @trailer.url_document %></td>
      </tr>
      <tr>
        <th scope="row">Fecha de lanzamiento suscriptor normal: </th>
        <td><%= @trailer.normal_release_date %></td>
      </tr>
      <tr>
        <th scope="row">Fecha de lanzamiento suscriptor premium: </th>
        <td><%= @trailer.premium_release_date %></td>
      </tr>
    </tbody>
  </table>
<% end %>
<embed src=<%=  @trailer.url_document+'#toolbar=0' %> type="application/pdf" width="100%" height="1000" style="margin:10px;">
<%= link_to 'Regresar', url_for(:back) %>